project_name: kubesense
before:
  hooks:
    - go mod tidy
builds:
  -
    main: main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - '-X kubesense.ai/cmd.BinaryVersion={{ .Version }}'
archives:
  -
    format: tar.gz
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    files:
      - none*
checksum:
  algorithm: sha256
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums'
changelog:
  use: github-native
snapshot:
  name_template: "{{ incpatch .Version }}-next"
